# Task 5 排序 搜索 计数和集合

## 1、排序
- numpy.sort(a[,axis=-1,kind='quicksort',order=None])
- axis: 排序沿数组的轴方向，0表示按行，1表示按列，None默认-1表示沿最后的轴排序
- kind: 提供了快排’quicksort‘，混排，堆排，默认为快排

In [1]:
import numpy as np
np.random.seed(2020)
x = np.random.rand(5, 5)*10
x = np.around(x,2)
print(x)

[[9.86 8.73 5.1  2.72 3.37]
 [2.17 2.76 3.43 8.62 1.57]
 [1.41 7.57 7.36 3.56 3.41]
 [6.67 2.17 5.61 1.24 3.2 ]
 [9.53 1.37 5.69 9.76 5.03]]


In [2]:
print(np.sort(x))

[[2.72 3.37 5.1  8.73 9.86]
 [1.57 2.17 2.76 3.43 8.62]
 [1.41 3.41 3.56 7.36 7.57]
 [1.24 2.17 3.2  5.61 6.67]
 [1.37 5.03 5.69 9.53 9.76]]


In [4]:
print(np.sort(x, axis=0))

[[1.41 1.37 3.43 1.24 1.57]
 [2.17 2.17 5.1  2.72 3.2 ]
 [6.67 2.76 5.61 3.56 3.37]
 [9.53 7.57 5.69 8.62 3.41]
 [9.86 8.73 7.36 9.76 5.03]]


In [5]:
print(np.sort(x, axis=1))

[[2.72 3.37 5.1  8.73 9.86]
 [1.57 2.17 2.76 3.43 8.62]
 [1.41 3.41 3.56 7.36 7.57]
 [1.24 2.17 3.2  5.61 6.67]
 [1.37 5.03 5.69 9.53 9.76]]


In [9]:
dt = np.dtype([('name', 'S10'),('age',np.int)])
a = np.array([('Mike',21), ('Nancy', 25), ('Bob',17),('July', 27)], dtype=dt)
print(np.sort(a, order='name'))

[(b'Bob', 17) (b'July', 27) (b'Mike', 21) (b'Nancy', 25)]


In [10]:
print(np.sort(a, order='age'))

[(b'Bob', 17) (b'Mike', 21) (b'Nancy', 25) (b'July', 27)]


### 1）numpy.argsort()
- 指定排序类型后，返回排序数组中数据的原来索引，默认按axis=1

In [11]:
# 一维数组
np.random.seed(2020)
x = np.random.randint(0,10,5)
print(x)

[0 8 3 6 3]


In [15]:
y = np.argsort(x)
print(y)
print('*'*20)
print(x[y])

[0 2 4 3 1]
********************
[0 3 3 6 8]


In [20]:
# 二维数组
np.random.seed(2020)
x = np.random.rand(3, 3) * 10
x = np.around(x, 2)
print(x)
print('*'*20)
y = np.argsort(x)
print(y)
print('*'*20)

# 返回的结果代表的意思是：
#     返回列表是按行从大到小排列的，只是显示的是数据在原来数组的索引位置

[[9.86 8.73 5.1 ]
 [2.72 3.37 2.17]
 [2.76 3.43 8.62]]
********************
[[2 1 0]
 [2 0 1]
 [0 1 2]]
********************


In [21]:
# 返回列表是按行从大到小排列的，只是显示的是数据在原来数组的索引位置
print(np.argsort(x, axis=1))

[[2 1 0]
 [2 0 1]
 [0 1 2]]


In [22]:
# 返回列表是按列从大到小排列的，只是显示的是数据在原来数组的索引位置
print(np.argsort(x, axis=0))

[[1 1 1]
 [2 2 0]
 [0 0 2]]


In [27]:
# np.take(a, indices,axis=None,mode='raise')沿轴从数组中获取元素
y = np.array([np.take(x[i], np.argsort(x[i])) for i in range(3)])
print(y)

array([[5.1 , 8.73, 9.86],
       [2.17, 2.72, 3.37],
       [2.76, 3.43, 8.62]])

### 2）numpy.lexsort()
- numpy.lexsort(keys[, axis=-1]) Perform an indirect stable sort using a sequence of keys.（使用键序列执行间接稳定排序。）

In [33]:
import numpy as np
np.random.seed(2020)
x = np.random.rand(3, 3) * 10
x = np.around(x, 2)
print(x)

[[9.86 8.73 5.1 ]
 [2.72 3.37 2.17]
 [2.76 3.43 8.62]]


In [35]:
# 返回按照第一列的升序，对应的在原来数组里的索引位置
index = np.lexsort([x[:,0]])
print(index)

[1 2 0]


In [36]:
y = x[index]
print(y)

[[2.72 3.37 2.17]
 [2.76 3.43 8.62]
 [9.86 8.73 5.1 ]]


In [38]:
z = x[np.lexsort([-1 * x[:,0]])]
print(z)

[[9.86 8.73 5.1 ]
 [2.76 3.43 8.62]
 [2.72 3.37 2.17]]


In [40]:
import numpy as np
x = np.array([1,5,1,4,3,4])
y = np.array([9,4,0,4,2,1])

a = np.lexsort([x])
b = np.lexsort([y])

print(a)
print(x[a])
print('*'*10)
print(b)
print(y[b])

[0 2 4 3 5 1]
[1 1 3 4 4 5]
**********
[2 5 4 1 3 0]
[0 1 2 4 4 9]


In [41]:
# 先按x排序，当x的值相同时，按y排序
# 参考：https://blog.csdn.net/u013066730/article/details/96485837
print(np.lexsort([y,x]))

[2 0 4 5 3 1]


In [42]:
# 先按y排序，当y的值相同时，按x排序
print(np.lexsort([x,y]))

[2 5 4 3 1 0]


### 3）numpy.partition()
- numpy.partition(a, kth, axis=-1, kind='introselect', order=None) Return a partitioned copy of an array.

In [43]:
np.random.seed(2020)
x = np.random.randint(1, 30, [8,3])
print(x)

[[ 1  9  4]
 [23  4 28]
 [ 4  8 25]
 [17  1 25]
 [11 10 20]
 [12 24 19]
 [ 4  7  6]
 [17 29 21]]


In [44]:
print(np.sort(x, axis=0))

[[ 1  1  4]
 [ 4  4  6]
 [ 4  7 19]
 [11  8 20]
 [12  9 21]
 [17 10 25]
 [17 24 25]
 [23 29 28]]


In [48]:
# 选取每一列的第三小的数
z = np.partition(x, kth=2, axis=0)
print(z)
print(z[2])

[[ 1  1  4]
 [ 4  4  6]
 [ 4  7 19]
 [17  9 25]
 [11 10 20]
 [12 24 25]
 [23  8 28]
 [17 29 21]]
[ 4  7 19]


In [49]:
# 选取每一列的第三大的数据
z = np.partition(x, kth=-3, axis=0)
print(z)
print(z[-3])

[[12  7 20]
 [ 1  1  4]
 [ 4  8  6]
 [ 4  4 19]
 [11  9 21]
 [17 10 25]
 [23 24 25]
 [17 29 28]]
[17 10 25]


### 4) numpy.argmax()
- numpy.argmax(a[, axis=None, out=None])
  Returns the indices of the maximum values along an axis

In [51]:
np.random.seed(2020)
x = np.random.rand(3, 3) * 10
x = np.around(x, 2)
print(x)

[[9.86 8.73 5.1 ]
 [2.72 3.37 2.17]
 [2.76 3.43 8.62]]


In [52]:
print(np.argmax(x)) # 全局最大的一个元素
print(np.argmax(x, axis=0))
print(np.argmax(x, axis=1))

0
[0 0 2]
[0 1 2]


### 5) numpy.argmin()

In [53]:
np.random.seed(2020)
x = np.random.rand(3, 3) * 10
x = np.around(x, 2)
print(x)
print('*'*10)
print(np.argmin(x)) # 全局最小的一个元素
print(np.argmin(x, axis=0))
print(np.argmin(x, axis=1))

[[9.86 8.73 5.1 ]
 [2.72 3.37 2.17]
 [2.76 3.43 8.62]]
**********
5
[1 1 1]
[2 2 0]


### 6）numpy.nonzero() 其值为非零元素的下标在对应轴上的值

In [54]:
# 一维数组
x = np.array([0, 0, 3, 2])
print(x)

y = np.nonzero(x)
print(y)

[0 0 3 2]
(array([2, 3]),)


In [59]:
print(y)
z = np.array(y)
print(z.shape)
print(z.ndim)

(array([2, 3]),)
(1, 2)
2


In [61]:
print(np.transpose(y))
print(x[np.nonzero(x)])

[[2]
 [3]]
[3 2]


In [65]:
# 二维数组
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
print(np.nonzero(x))
print(np.array(np.nonzero(x)))

[[3 0 0]
 [0 4 0]
 [5 6 0]]
(array([0, 1, 2, 2]), array([0, 1, 0, 1]))
[[0 1 2 2]
 [0 1 0 1]]


#### nonzero()将布尔数组转换成整数数组进行操作

In [66]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
print(x>3)
print(x[x>3])

[[False False False]
 [ True  True  True]
 [ True  True  True]]
[4 5 6 7 8 9]


In [68]:
print(np.nonzero(x>3))

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))


### 7) numpy.where
- numpy.where(condition, [x=None, y=None]) Return elements chosen from x or y depending on condition.

In [71]:
# 满足条件，输出x, 不满足输出y
x = np.arange(10)
print(x)

print(np.where(x<5, x, x*10))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


In [72]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.where(x > 5)
print(y)
print(x[y])
print('*'*20)

y = np.nonzero(x > 5)
print(y)
print(x[y])
print('*'*20)

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.where(x > 25)
print(y)
print(x[y])
print('*'*20)

y = np.nonzero(x > 25)
print(y)
print(x[y])
print('*'*20)

(array([5, 6, 7]),)
[6 7 8]
********************
(array([5, 6, 7]),)
[6 7 8]
********************
(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))
[26 27 28 29 30 31 32 33 34 35]
********************
(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))
[26 27 28 29 30 31 32 33 34 35]
********************


### 8) numpy.count_nonzero()
- numpy.count_nonzero(a, axis=None) Counts the number of non-zero values in the array a.

In [75]:
import numpy as np
print(np.eye(4))
x = np.count_nonzero(np.eye(4))
print(x)

x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]])
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4
5


In [76]:
x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]], axis=0)
print(x)

[1 1 1 1 1]


In [77]:
x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]], axis=1)
print(x) 

[2 3]


## 2. 集合操作

### 1）构造集合
- numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None) Find the unique elements of an array.
- return_index=True 表示返回新列表元素在旧列表中的位置。
- return_inverse=True表示返回旧列表元素在新列表中的位置。
- return_counts=True表示返回新列表元素在旧列表中出现的次数

In [78]:
import numpy as np
x = np.unique([1,2,3,2,1,3])
print(x)

[1 2 3]


In [79]:
x = np.array([[1,1],[2,3]])
print(np.unique(x))      

[1 2 3]


In [80]:
x = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
print(np.unique(x, axis=0))

[[1 0 0]
 [2 3 4]]


In [82]:
# return_index = True 返回新列表元素在旧列表中的位置
x = np.array(['a', 'b', 'b', 'c', 'a'])
u, index = np.unique(x, return_index=True)
print(u)
print(index)

['a' 'b' 'c']
[0 1 3]


In [83]:
# return_inverse=True, 返回旧元素在新列表中的位置
x = np.array([1, 2, 6, 4, 2, 3, 2])
u, index = np.unique(x, return_inverse=True)
print(u)
print(index)

[1 2 3 4 6]
[0 1 4 3 1 2 1]


In [84]:
u, count = np.unique(x, return_counts=True)
print(u)
print(count)

[1 2 3 4 6]
[1 3 1 1 1]


### 2) 布尔运算
- numpy.in1d(ar1, ar2, assume_unique=False, invert=False) Test whether each element of a 1-D array is also present in a second array. 前面的数组是否包含后面的数组，返回布尔值

In [85]:
x = np.array([0,1,2,5,0])
s = [0,2]
mask = np.in1d(x,s)
print(mask)
print(x[mask])

print(np.in1d(x,s,invert=True))

[ True False  True False  True]
[0 2 0]
[False  True False  True False]


### 3）两个集合的交集
- numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False) Find the intersection of two arrays.
Return the sorted, unique values that are in both of the input arrays.

In [86]:
x = np.intersect1d([1,3,4,3],[3,1,2,1])
print(x)

[1 3]


In [87]:
x = np.array([1, 1, 2, 3, 4])
y = np.array([2, 1, 4, 6])
xy, x_ind, y_ind = np.intersect1d(x, y, return_indices=True)

In [88]:
print(xy)
print(x_ind)  
print(y_ind)


[1 2 4]
[0 2 4]
[1 0 2]


In [89]:
from functools import reduce

x = reduce(np.intersect1d, ([1,3,4],[3,1,2],[5,1,3]))
print(x)

[1 3]


### 3）两个集合的并集
- numpy.union1d(ar1, ar2) Find the union of two arrays.
Return the unique, sorted array of values that are in either of the two input arrays.

In [90]:
import numpy as np
from functools import reduce

x = np.union1d([-1, 0, 1], [-2, 0, 2])
print(x)
x = reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
print(x) 

[-2 -1  0  1  2]
[1 2 3 4 6]


### 4）求两个集合的差集：

- `numpy.setdiff1d(ar1, ar2, assume_unique=False)` Find the set difference of two arrays.

In [95]:
# 集合的差，即元素存在于第一个函数不存在于第二个函数中。
import numpy as np

a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
print(np.setdiff1d(b,a))

[5 6]


### 5) 求两个集合的异或：
- setxor1d(ar1, ar2, assume_unique=False) Find the set exclusive-or of two arrays.

In [96]:
# 两个集合交集的补集。也就是两个数组中各自独自拥有的元素的集合。
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
print(np.setxor1d(a,b))

[1 2 5 6]
