# 练习题

### 1. 只打印或显示numpy数组的小数点后3位

In [1]:
import numpy as np
x = np.random.random([5,3])
print(x)

[[0.40205808 0.14788131 0.69264165]
 [0.5393362  0.16990795 0.22458372]
 [0.95555203 0.41763862 0.78142473]
 [0.28725286 0.08599749 0.56833207]
 [0.11344575 0.68587708 0.35645845]]


In [2]:
np.around(x,3)

array([[0.402, 0.148, 0.693],
       [0.539, 0.17 , 0.225],
       [0.956, 0.418, 0.781],
       [0.287, 0.086, 0.568],
       [0.113, 0.686, 0.356]])

In [6]:
np.set_printoptions(precision=3)
print(x)

[[0.402 0.148 0.693]
 [0.539 0.17  0.225]
 [0.956 0.418 0.781]
 [0.287 0.086 0.568]
 [0.113 0.686 0.356]]


### 2. 将numpy数组a中打印的项数限制为最多6个元素

In [7]:
a = np.arange(10)
np.set_printoptions(threshold=6)
print(a)

[0 1 2 ... 7 8 9]


### 3. 打印完整的numpy数组而不中断

In [8]:
a = np.arange(20)
np.set_printoptions(threshold=7)
print(a)
np.set_printoptions(threshold=np.iinfo(np.int).max)
print(a)

[ 0  1  2 ... 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [13]:
a = np.arange(20)
np.set_printoptions(threshold=7)
print(a)

np.set_printoptions(threshold=len(a))
print(a)

[ 0  1  2 ... 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### 4. 创建一个形为5×3的二维数组，以包含5到10之间的随机数

In [14]:
a = np.random.randint(5, 10, (5,3))
print(a)

[[7 9 9]
 [6 8 9]
 [9 5 6]
 [6 6 9]
 [5 9 8]]


In [15]:
b = np.random.uniform(5,10,[5,3])
print(b)

[[7.391 8.673 9.334]
 [9.081 7.004 7.773]
 [7.854 6.23  9.458]
 [5.633 9.27  8.294]
 [5.615 7.367 5.637]]


### 5. 计算给定数组中每行的最大值

In [16]:
np.random.seed(100)
a = np.random.randint(1, 10, [5, 3])
print(a)

b = np.argmax(a, axis=1)
print(b)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[0 0 2 0 2]


### 6. 计算两个数组a和数组b之间的欧氏距离

In [17]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

# 方法一：
x = np.sqrt(np.sum((a-b)**2))
print(x)

# 方法二：
y = np.linalg.norm(a-b)
print(y)

6.708203932499369
6.708203932499369


### 7. 计算矩阵的行列式和矩阵的逆

In [18]:
a = np.diag([5,5,5,5,5])
np.linalg.det(a)

3124.999999999999

In [19]:
np.linalg.inv(a)

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])