# 练习 - 排序搜索计数

### 1. 如何通过第n列对一个数组进行排序 

In [3]:
import numpy as np
x = np.random.randint(0,10,(3,3))
print(x)

[[7 5 4]
 [5 2 5]
 [0 1 0]]


In [6]:
x[np.argsort(x[:,-1])]

array([[0, 1, 0],
       [7, 5, 4],
       [5, 2, 5]])

### 2. 从arr中提取所有奇数

In [7]:
x = np.arange(10)
index = np.where(x%2==1)
print(x[index])

[1 3 5 7 9]


In [8]:
x[x%2==1]

array([1, 3, 5, 7, 9])

### 3. 将arr中的偶数元素替换为0

In [12]:
x = np.arange(10)
x = np.where(x%2==0, 0, x)
x

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

### 4. 将 arr 中的所有偶数元素替换为0，而不改变arr

In [13]:
x = np.arange(10)
y = np.where(x%2==0, 0, x)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
y = np.copy(x)
y[y%2==0]=0
print(y)
print(x)

[0 1 0 3 0 5 0 7 0 9]
[0 1 2 3 4 5 6 7 8 9]


### 5. 获取给定数组中前5个最大值的位置

In [18]:
np.random.seed(2020)
x = np.random.uniform(1, 50, 20)
print(x)
print('*'*50)
# 1.方法一
b = np.argsort(x)
print(b[-5:])

[49.32756461 43.79620535 25.97753072 14.31995    17.50901766 11.63075899
 14.54738001 17.82246405 43.24578784  8.67828383  7.903475   38.09693375
 37.07992099 18.42749149 17.71355781 33.67334948 11.6379313  28.50992214
  7.08476011 16.66708774]
**************************************************
[12 11  8  1  0]


In [22]:
# 方法二
b = np.sort(x)
print(np.where(x>=b[-5]))

(array([ 0,  1,  8, 11, 12]),)


In [23]:
# 方法三
b = np.argpartition(x, kth=-5)
print(b[-5:])

[12 11  8  1  0]


### 6. 删除一维numpy数组中所有NaN值

In [26]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
c = np.logical_not(np.isnan(a))
print(c)
print(a[c])

[ True  True  True False  True  True  True False]
[1. 2. 3. 5. 6. 7.]


### 7. 获取数组a和数组b之间的公共项。

In [27]:

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
x = np.intersect1d(a, b)
print(x) 

[2 4]


### 8. 从数组a中删除数组b中的所有项

In [28]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
x = np.setdiff1d(a, b)
print(x)

[1 2 3 4]
