# Task 4 数学函数和逻辑函数

## 1. 向量化和广播

广播机制描述了numpy如何在算术运算期间处理具有不同形状的数组。

若两个数组的每一维度等长，或者其中一个数组时一维，那么广播机制就适用。如果这两个条件不满足，numpy就会抛出异常，说明两个数组不兼容。

总结来说，广播的规则有三个：
- 如果两个数组的维度数dim不相同，那么小维度数组的形状将会在左边补1。
- 如果shape维度不匹配，但是有维度是1，那么可以扩展维度是1的维度匹配另一个数组；
- 如果shape维度不匹配，但是没有任何一个维度是1，则匹配引发错误；

In [26]:
import numpy as np

x = np.arange(4)
y = np.ones((3, 4))
print(x)
print(y)

print((x + y).shape)
print(x + y)

[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [28]:
# 两个数组都需要广播
x = np.arange(4).reshape(4,1)
y = np.ones(5)
print(x)
print(y)
print('*'*20)
print(x+y)
print((x+y).shape)

[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
********************
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
(4, 5)


In [31]:
x = np.array([0.0, 10.1, 20.2, 30.3])
y = np.array([5.0, 6.0, 7.0])
z = x[:, np.newaxis] + y
print(z.shape)
print(z)

(4, 3)
[[ 5.   6.   7. ]
 [15.1 16.1 17.1]
 [25.2 26.2 27.2]
 [35.3 36.3 37.3]]


In [32]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## 2. 算术运算
- numpy.add
- numpy.substract
- numpy.multiply
- numpy.divide
- numpy.floor_divide
- numpy.power

在 numpy 中对以上函数进行了运算符的重载，且运算符为 元素级。也就是说，它们只用于位置相同的元素之间，所得到的运算结果组成一个新的数组。


In [35]:
x = np.array([1, 2, 3])
print(np.add(x, 1))
print(np.subtract(x,1))
print(np.multiply(x,2))

[2 3 4]
[0 1 2]
[2 4 6]


In [37]:
print(np.divide(x,2))        # 相当于 x/2
print(np.floor_divide(x, 2)) # 相当于 x//2

[0.5 1.  1.5]
[0 1 1]


In [38]:
print(np.power(x,2))  # x**2

[1 4 9]


In [39]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(x.shape)

(5, 5)


In [40]:
# 相当于对 x 的每一个元素都操作了一遍
print(np.add(x, 1))
print('*'*30)
print(np.subtract(x,1))
print('*'*30)
print(np.multiply(x,2))
print('*'*30)
print(np.divide(x,2)) 
print('*'*30)
print(np.floor_divide(x, 2))

[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]
 [32 33 34 35 36]]
******************************
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
******************************
[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]
******************************
[[ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]
 [13.  13.5 14.  14.5 15. ]
 [15.5 16.  16.5 17.  17.5]]
******************************
[[ 5  6  6  7  7]
 [ 8  8  9  9 10]
 [10 11 11 12 12]
 [13 13 14 14 15]
 [15 16 16 17 17]]


In [42]:
# 广播机制
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

y = np.arange(1, 6)
print(x.shape)
print(y)

(5, 5)
[1 2 3 4 5]


In [43]:
print(np.add(x, y))
print('*'*30)
print(np.subtract(x, y))
print('*'*30)
print(np.multiply(x, y))
print('*'*30)
print(np.divide(x, y)) 
print('*'*30)
print(np.floor_divide(x, y))

[[12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]
 [27 29 31 33 35]
 [32 34 36 38 40]]
******************************
[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]
******************************
[[ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]
 [ 31  64  99 136 175]]
******************************
[[11.          6.          4.33333333  3.5         3.        ]
 [16.          8.5         6.          4.75        4.        ]
 [21.         11.          7.66666667  6.          5.        ]
 [26.         13.5         9.33333333  7.25        6.        ]
 [31.         16.         11.          8.5         7.        ]]
******************************
[[11  6  4  3  3]
 [16  8  6  4  4]
 [21 11  7  6  5]
 [26 13  9  7  6]
 [31 16 11  8  7]]


### numpy.sqrt()
### numpy.square()

In [44]:
x = np.arange(1,5)
print(x)
print(np.sqrt(x))
print(np.power(x, 0.5))
print(np.square(x))
print(np.power(x, 2))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]
[ 1  4  9 16]


## 3. 三角函数
- numpy.sin
- numpy.cos
- numpy.tan
- numpy.arcsin
- numpy.arccos
- numpy.arctan

In [47]:
x = np.linspace(0, np.pi/2, num=10)
x

array([0.        , 0.17453293, 0.34906585, 0.52359878, 0.6981317 ,
       0.87266463, 1.04719755, 1.22173048, 1.3962634 , 1.57079633])

In [48]:
y = np.sin(x)
print(y)
print(np.arcsin(y))

[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254  0.93969262 0.98480775 1.        ]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]


### 指数和对数
### numpy.exp
### numpy.log， base - e
### numpy.exp2
### numpy.log2
### numpy.log10

In [50]:
import numpy as np

x = np.arange(1, 5)
print(x)
y = np.exp(x)
print(y)
print(np.log(y))

[1 2 3 4]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1. 2. 3. 4.]


## 4. 加法函数和乘法函数
- numpy.sum(a, axis=None,...)
axis=i，则numpy沿着第i个下标变化的方向进行操作。

如果不设置，那么对所有的元素操作；

如果axis=0，则沿着纵轴进行操作；

axis=1，则沿着横轴进行操作。

- numpy.cumsum(a, axis=None, dtype=None, out=None)
聚合函数是指对一组值（比如一个数组）进行操作，返回一个单一值作为结果的函数。因而，求数组所有元素之和的函数就是聚合函数。ndarray类实现了多个这样的函数。

In [51]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(np.sum(x))
print('*'*20)
print(np.sum(x, axis=0))
print('*'*20)
print(np.sum(x, axis=1))


575
********************
[105 110 115 120 125]
********************
[ 65  90 115 140 165]


In [55]:
x = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])

In [56]:
# 返回给定轴上的数组元素的累加和
print(np.cumsum(x))
print('*'*20)
print(np.cumsum(x, axis=0))
print('*'*20)
print(np.cumsum(x, axis=1))

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
********************
[[ 1  2  3  4  5]
 [ 7  9 11 13 15]
 [18 21 24 27 30]]
********************
[[ 1  3  6 10 15]
 [ 6 13 21 30 40]
 [11 23 36 50 65]]


## 5. 差值和四舍五入
- numpy.diff(a, n=1, axis=-1, prepend=np._NoValue, append=np._NoValue)
a：输入矩阵
n：可选，代表要执行几次差值
axis：默认是最后一个

out[i] = a[i+1] - a[i]

In [58]:
x = np.arange(2, 14).reshape(3,4)
x

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [60]:
x[1,1] = 8
print(x)
print('*'*20)
print(np.diff(x))
print('*'*20)
print(np.diff(x, axis=0))

[[ 2  3  4  5]
 [ 6  8  8  9]
 [10 11 12 13]]
********************
[[1 1 1]
 [2 0 1]
 [1 1 1]]
********************
[[4 5 4 4]
 [4 3 4 4]]


In [62]:
# numpy.around(a, decimal=0, out=None)
# 将数组舍入到给定的小数位数, 默认是0

x = np.random.rand(3,3)*10
print(x)
print(np.around(x))
print(np.around(x,2))

[[6.24745894 8.49629172 1.22056499]
 [5.94693213 6.90081335 8.1767692 ]
 [8.58177677 4.13428319 8.34781889]]
[[6. 8. 1.]
 [6. 7. 8.]
 [9. 4. 8.]]
[[6.25 8.5  1.22]
 [5.95 6.9  8.18]
 [8.58 4.13 8.35]]


## 6. 上下限
- numpy.ceil()
- numpy.floor()

In [65]:
x = np.random.rand(2,2) * 10
print(x)
print(np.ceil(x))
print(np.floor(x))

[[9.93440929 0.53525818]
 [0.79182643 7.97037478]]
[[10.  1.]
 [ 1.  8.]]
[[9. 0.]
 [0. 7.]]


In [66]:
# 裁剪（限制）数组中的值。
import numpy as np

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.clip(x, a_min=20, a_max=30)
print(y)

[[20 20 20 20 20]
 [20 20 20 20 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [30 30 30 30 30]]


In [77]:
# numpy.absolute()
# numpy.abs() 简写
import numpy as np

x = np.arange(-3,6)
print(x)
print(np.abs(x))
print(np.absolute(x))

[-3 -2 -1  0  1  2  3  4  5]
[3 2 1 0 1 2 3 4 5]
[3 2 1 0 1 2 3 4 5]


In [78]:
print(np.sign(x))

[-1 -1 -1  0  1  1  1  1  1]


# 逻辑函数部分 

## 1.  真值测试
- numpy.all
- numpy.any

- numpy.isnan()

In [82]:
import numpy as np
x = np.array([1,3,5])
y = np.copy(x)


True
True


In [83]:
y[0] = 10
print(np.all(x==y))
print(np.any(x==y))

False
True


In [85]:
x = np.eye(3)
print(np.all(x, axis=0))  # [False False False]
print(np.any(x, axis=0))  # [ True  True  True]

[False False False]
[ True  True  True]


In [86]:
x = np.array([1,2,np.nan])
print(np.isnan(x))

[False False  True]


## 2. 逻辑运算
- numpy.logical_not：逻辑非
- numpy.logical_and：逻辑与
- numpy.logical_or： 逻辑或
- numpy.logical_xor：逻辑异或

In [89]:
print(np.logical_not([True, False, 0, 1]))

x = np.arange(5)
print(x)
print(np.logical_not(x < 3))
print('*'*20)

# 逐元素计算x1 AND x2元素的真值。
print(np.logical_and(True, False))  
print(np.logical_and([True, False], [True, False]))
print(np.logical_and(x > 1, x < 4))
print('*'*20)

# 逐元素计算x1 OR x2的真值。
print(np.logical_or(True, False))
print(np.logical_or([True, False], [False, False]))
print(np.logical_or(x < 1, x > 3))
print('*'*20)

# 逐元素计算x1 XOR x2的真值
print(np.logical_xor(True, False))
print(np.logical_xor([True, True, False, False], [True, False, True, False]))
print(np.logical_xor(x < 1, x > 3))
print(np.logical_xor(0, np.eye(2)))

[False  True  True False]
[0 1 2 3 4]
[False False False  True  True]
********************
False
[ True False]
[False False  True  True False]
********************
True
[ True False]
[ True False False False  True]
********************
True
[False  True  True False]
[ True False False False  True]
[[ True False]
 [False  True]]


In [97]:
x = np.array([[11, 12, 13, 14],
              [16, 17, 18, 19],
              [21, 22, 23, 24]])

y = x > 20
print(y)
print(np.greater(x, 20))

[[False False False False]
 [False False False False]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [ True  True  True  True]]


In [98]:
y = x >= 20
print(y)
print(np.greater_equal(x, 20))

[[False False False False]
 [False False False False]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [ True  True  True  True]]


In [99]:
y = x == 22
print(y)
print(np.equal(x, 22))

[[False False False False]
 [False False False False]
 [False  True False False]]
[[False False False False]
 [False False False False]
 [False  True False False]]


In [101]:
y = x < 20
# print(y)
print(np.less(x, 20))
print('*'*50)
y = x <= 20
# print(y)
print(np.less_equal(x, 20))

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]
**************************************************
[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]
