## 数组练习

**将 `arr`转换为2行的2维数组。**
- `arr = np.arange(10)`

In [2]:
import numpy as np

arr = np.arange(10)

# 方法1
x = np.reshape(arr, [2, 5])
print(x)

# 方法2
x = np.reshape(arr, [2, -1])
print(x)

# 方法3
x = np.reshape(arr, [-1, 2])
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**垂直堆叠数组a和数组b。**
- `a = np.arange(10).reshape([2, -1])`
- `b = np.repeat(1, 10).reshape([2, -1])`

In [7]:
import numpy as np
a = np.arange(10).reshape([2,-1])
b = np.repeat(1,10).reshape([2, -1])

print(np.concatenate([a,b], axis=0))
print(np.vstack([a, b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


**水平堆叠数组a与数组b。**
- `a = np.arange(10).reshape([2, -1])`
- `b = np.repeat(1, 10).reshape([2, -1])`

In [8]:
import numpy as np
a = np.arange(10).reshape([2,-1])
b = np.repeat(1,10).reshape([2, -1])

print(np.concatenate([a,b], axis=1))
print(np.hstack([a, b]))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


**将 `arr`的2维数组按列输出。**
- `arr =  np.array([[16, 17, 18, 19, 20],[11, 12, 13, 14, 15],[21, 22, 23, 24, 25],[31, 32, 33, 34, 35],[26, 27, 28, 29, 30]])`

In [9]:
arr =  np.array([[16, 17, 18, 19, 20],[11, 12, 13, 14, 15],[21, 22, 23, 24, 25],[31, 32, 33, 34, 35],[26, 27, 28, 29, 30]])
print(arr.flatten(order='F'))

[16 11 21 31 26 17 12 22 32 27 18 13 23 33 28 19 14 24 34 29 20 15 25 35
 30]


**给定两个随机数组A和B，验证它们是否相等。**

- A = np.random.randint(0,2,5) 
- B = np.random.randint(0,2,5)

In [14]:
A = np.array([1,2,3])
B = np.array([1,2,3]) 
equal = np.allclose(A, B)
print(equal)
equal2 = np.array_equal(A, B)
print(equal2)

True
True


**在给定的numpy数组中找到重复的条目（第二次出现以后），并将它们标记为True。第一次出现应为False。**

- `a = np.random.randint(0, 5, 10)`

In [26]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)
b = np.full(10, True)
values, indexs = np.unique(a, return_index=True)
b[indexs] = False
print(b)

[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


In [27]:
values

array([0, 2, 3, 4])

In [28]:
indexs

array([0, 4, 2, 5])

**建立一个随机数在1-10之间的3行2列的数组，并将其转换成2行3列的数组。**

In [30]:
import numpy as np
x = np.random.randint(1,10,size=[3, 2])
print(x)
print('*'*20)
print(np.reshape(x,[2,3]))

[[1 7]
 [3 5]
 [2 6]]
********************
[[1 7 3]
 [5 2 6]]


In [31]:
x

array([[1, 7],
       [3, 5],
       [2, 6]])

In [33]:
x.reshape([2, 3])

array([[1, 7, 3, 5, 2, 6]])